services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - API_KEY=kuncirahasia123
    volumes:
      # Mounting folder agar file .db tidak hilang saat restart
      - ./data_sqlite:/usr/src/app/data
    restart: always